name = "portfolio-cms-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
account_id = "84ecd2ee1ee7671dc35a4ef3b56e16b0"

[vars]
ENVIRONMENT = "development"
ADMIN_USERNAME = "admin"
ALLOWED_ORIGIN_PROD = "http://localhost:3000"            # TEMP: using local until real prod domain is given
ALLOWED_ORIGIN_DEV  = "http://localhost:3000"            # Vite dev server (NOT :4200)
R2_PUBLIC_URL = "https://pub-6b37856b9c4e4ea5b0581e9b4e646c2b.r2.dev"

[[r2_buckets]]
binding = "CMS_BUCKET"
bucket_name = "mdfayaz"
preview_bucket_name = "mdfayaz"
